---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/diegochavezcarro/organization-rest-panache.git
    app.quarkus.io/build-timestamp: 2020-11-03 - 21:55:10 +0000
    app.quarkus.io/commit-id: abd71c691d3d87231ee0b5f7c1391db33d9d921d
  labels:
    app.kubernetes.io/name: organization-rest-panache
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: organization-rest-panache
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    app.kubernetes.io/name: organization-rest-panache
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://github.com/diegochavezcarro/organization-rest-panache.git
    app.quarkus.io/build-timestamp: 2020-11-03 - 21:55:10 +0000
    app.quarkus.io/commit-id: abd71c691d3d87231ee0b5f7c1391db33d9d921d
  labels:
    app.kubernetes.io/name: organization-rest-panache
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: organization-rest-panache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: organization-rest-panache
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://github.com/diegochavezcarro/organization-rest-panache.git
        app.quarkus.io/build-timestamp: 2020-11-03 - 21:55:10 +0000
        app.quarkus.io/commit-id: abd71c691d3d87231ee0b5f7c1391db33d9d921d
      labels:
        app.kubernetes.io/name: organization-rest-panache
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
      - env:
        - name: POSTGRESQL_SERVICE_HOST
          value: 192.168.0.236
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: diegochavezcarro/organization-rest-panache:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: organization-rest-panache
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
